apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- cert-manager-certificate-cluster-issuer.yaml

namespace: dns-infra

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
- behavior: create
  envs: [env-vars]
  name: cert-manager-env-vars    

components:
  - ../../components/replacements

replacements:
- source: 
    kind: ConfigMap
    name: cert-manager-env-vars
    fieldPath: data.PROJECT_ID
  targets:
  - select:
      name: letsencrypt-${DEPLOY_ENV}-gcp
      kind: ClusterIssuer
    fieldPaths:
    - spec.acme.solvers.0.dns01.cloudDNS.project

  - select:
      name: letsencrypt-${DEPLOY_ENV}-gcp
      kind: ClusterIssuer
    fieldPaths:
    - spec.acme.solvers.0.selector.dnsZones.0
    options:
      delimiter: "."
      index: 0
