---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-${DEPLOY_ENV}-gcp
spec:
  acme:
    email: demo@odysseycloud.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-${DEPLOY_ENV}-gcp
    solvers:
      - dns01:
          cloudDNS:
            project: ${PROJECT_ID}
        selector:
          dnsZones:
          - '${DEPLOY_ENV}.odysseycloud.io'
