apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: ${PROJECT_ID}
  name: cert.manager
spec:
  title: cert-manager
  description: cert-manager
  permissions:
    - dns.changes.create
    - dns.changes.get
    - dns.changes.list
    - dns.managedZones.list
    - dns.resourceRecordSets.create
    - dns.resourceRecordSets.delete
    - dns.resourceRecordSets.get
    - dns.resourceRecordSets.list
    - dns.resourceRecordSets.update
  stage: GA
  