apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: cert-manager
  annotations:
    cnrm.cloud.google.com/project-id: ${PROJECT_ID}
spec:
  displayName: cert-manager