namespace: dns-infra
helmCharts:
- name: cert-manager
  version: 1.11.0
  repo: https://charts.jetstack.io
  releaseName: cert-manager
  includeCRDs: true
  namespace: dns-infra
  valuesFile: base-install.yaml

resources:
- IAMServiceAccount.yaml
- IAMPolicyMember.yaml
- IAMCustomRole.yaml